$(document).ready(function(){
	$('#edit-gk-vocab1-999').click(function(){
		$('#gk-serienbrief-taxonomy-form').toggleCheckboxes('.gk_vocab_class_1');
	});
	$('#edit-gk-vocab2-999').click(function(){
		$('#gk-serienbrief-taxonomy-form').toggleCheckboxes('.gk_vocab_class_2');
	});
	$('#edit-gk-vocab3-999').click(function(){
		$('#gk-serienbrief-taxonomy-form').toggleCheckboxes('.gk_vocab_class_3');
	});
	$('#edit-gk-vocab4-999').click(function(){
		$('#gk-serienbrief-taxonomy-form').toggleCheckboxes('.gk_vocab_class_4');
	});
	$('#edit-gk-vocab5-999').click(function(){
		$('#gk-serienbrief-taxonomy-form').toggleCheckboxes('.gk_vocab_class_5');
	});
}); 